# Generated by Django 5.0.6 on 2024-08-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.TextField(default='$2b$12$TgXwLftHEUgSVovnaesKGu9SFWu4GwHViqthpbQJxyHxIH/T8bgJK'),
        ),
    ]
