# Generated by Django 5.0.6 on 2024-08-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.TextField(),
        ),
    ]
