# Generated by Django 5.0.6 on 2024-08-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_admin_password_alter_admin_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Admins',
        ),
    ]
