# Generated by Django 5.0.6 on 2024-08-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_sem_branches_staff_student_subject_semexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stpassword',
            field=models.TextField(null=True),
        ),
    ]
