# Generated by Django 5.0.6 on 2024-08-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_student_stpassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semexam',
            old_name='stname',
            new_name='stud',
        ),
    ]
