# Generated by Django 5.0.6 on 2024-08-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_stname_semexam_stud'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Semexam',
        ),
    ]
