# Generated by Django 5.0.6 on 2024-08-29 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_semexam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semexam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('bname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.branches')),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sem')),
                ('staffname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff')),
                ('stud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
                ('subname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
            ],
        ),
    ]
