# Generated by Django 5.0.6 on 2024-09-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_student_setnewpsw'),
    ]

    operations = [
        migrations.CreateModel(
            name='messeges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('time', models.TextField()),
                ('date', models.TextField()),
                ('subject', models.TextField()),
                ('messege', models.TextField()),
            ],
        ),
    ]
