# Generated by Django 5.0.6 on 2024-09-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_messeges_read_alter_messeges_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
