# Generated by Django 5.0.6 on 2024-09-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_branches_status_staff_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='email',
            field=models.TextField(null=True),
        ),
    ]
